# Kopp14 Land water storage pipeline

pre-process:
  task1:
    executable: "singularity"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf kopp14_landwaterstorage_preprocess_data.tgz"
    pre_exec2: "module load singularity"
    executable_args: "exec"
    container: "kopp14_landwaterstorage.sif"
    container_args: "/usr/bin/python3"
    script: "kopp14_preprocess_landwaterstorage.py"
    options:
      - "dotriangular"
      - "includepokherl"
      - "pipeline_id"
    upload_input_data:
      - "./modules/kopp14/landwaterstorage/kopp14_landwaterstorage.sif"
      - "./modules/kopp14/landwaterstorage/kopp14_preprocess_landwaterstorage.py"
      - "./modules/kopp14/landwaterstorage/data/kopp14_landwaterstorage_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"
#      - "%PIPELINE_ID%_config.pkl"

fit:
  task1:
    executable: "singularity"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    pre_exec2: "module load singularity"
    executable_args: "exec"
    container: "kopp14_landwaterstorage.sif"
    container_args: "/usr/bin/python3"
    script: "kopp14_fit_landwaterstorage.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/landwaterstorage/kopp14_fit_landwaterstorage.py'
    copy_input_data:
      pre-process:
        task1:
          - "kopp14_landwaterstorage.sif"
          - "%PIPELINE_ID%_data.pkl"
          - "%PIPELINE_ID%_config.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "singularity"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    pre_exec2: "module load singularity"
    executable_args: "exec"
    container: "kopp14_landwaterstorage.sif"
    container_args: "/usr/bin/python3"
    script: "kopp14_project_landwaterstorage.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/landwaterstorage/kopp14_project_landwaterstorage.py'
    copy_input_data:
      pre-process:
        task1:
          - "kopp14_landwaterstorage.sif"
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

post-process:
    task1:
      executable: "singularity"
      cpu:
        processes: 1
        process-type: None
        threads-per-process: 1
        thread-type: None
      pre_exec: "tar -xzf kopp14_landwaterstorage_postprocess_data.tgz"
      pre_exec2: "module load singularity"
      executable_args: "exec"
      container: "kopp14_landwaterstorage.sif"
      container_args: "/usr/bin/python3"
      script: "kopp14_postprocess_landwaterstorage.py"
      options:
        - "site_ids"
        - "pipeline_id"
      upload_input_data:
        - './modules/kopp14/landwaterstorage/kopp14_postprocess_landwaterstorage.py'
        - './modules/kopp14/landwaterstorage/read_bkgdrate.py'
        - './modules/kopp14/landwaterstorage/data/kopp14_landwaterstorage_postprocess_data.tgz'
      copy_input_data:
        pre-process:
          task1:
            - "kopp14_landwaterstorage.sif"
        project:
          task1:
            - "%PIPELINE_ID%_projections.pkl"
      download_output_data:
        - "%PIPELINE_ID%_localsl.nc"
